Add Xiaomi Mi Band 3
vsoch/40-avocados pull request #34
Opened 2018-10-31 14:15 UTC by sergioedo

2018-10-31 14:24 UTC, vsoch commented
This wouldn't be affordable with $40 (it's $45) and it looks like the name is still "guitar-capo" ?

2018-10-31 16:56 UTC, vsoch requested changes
The PR needs to be updated with current master, the name correctly changed to something not "guitar-capo" and the pricing logic checked. Thanks!

2018-11-01 12:40 UTC, sergioedo commented
I've made a rebase to actual master and fixed my thing (name and img/url to amazon price is more stable, I think gearbest changes prices all the time)

2018-11-01 13:44 UTC, vsoch approved these changes

2018-11-01 13:44 UTC, merged